{% set name = "inotify_simple" %}
{% set version = "1.2.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: f5a7dd817122f64196da8ba9b24ec285181215a9f7503791e718b3cb342eaee6

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  skip: true  # [win]
  
requirements:
  host:
    - pip
    - python
    - enum34  # [py<34]
    
  run:
    - python
    - enum34  # [py<34]
    
test:
  requires:
    - enum34  # [py<34]
    
  imports:
    - inotify_simple

about:
  home: "https://github.com/chrisjbillington/inotify_simple"
  license: "BSD-2-Clause"
  license_family: "BSD"
  license_file: "LICENSE"
  summary: "A simple wrapper around inotify. No fancy bells and whistles, just a literal wrapper with ctypes. Only 127 lines of code!"
  doc_url: "https://pypi.org/project/inotify_simple/"
  dev_url: "https://github.com/chrisjbillington/inotify_simple"

extra:
  recipe-maintainers:
    - mwilson8
    - rluria14
